version: 1
formatters:
  console_formatter:
    format: "[%(asctime)s][%(levelname)s][%(filename)s:%(lineno)d] - %(message)s"
  file_formatter:
    format: "[%(asctime)s][%(name)20s][%(levelname)10s][%(threadName)10s][%(processName)10s][%(filename)20s:%(lineno)4d] - %(message)s"
handlers:
  console_handler:
    class: logging.StreamHandler
    level: INFO
    formatter: console_formatter
  file_handler:
    class: logging.handlers.RotatingFileHandler
    filename: run.log
    mode: "a"
    maxBytes: 1048576 # 1 * 1024 * 1024
    backupCount: 10
    encoding: "utf-8"
    level: DEBUG
    formatter: file_formatter
root:
  level: WARNING
loggers:
  "__main__":
    level: DEBUG
    handlers:
      - console_handler
      - file_handler
  "app":
    level: DEBUG
    handlers:
      - console_handler
      - file_handler
# disable_existing_loggers: true
disable_existing_loggers: false
